/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{html,vue,js,ts,jsx,tsx}"],
  theme: {
    colors: {
      black: "#000000",
      grey: "#595959",
      "light-grey": "#A6A6A6",
      green: "#01B812",
      "light-green": "#5AD165",
      "pale-green": "#A6E6AC",
      Red: "#FD0000",
      "light-red": "#FE5959",
      "pale-red": "#FEA6A6",
      yellow: "#FEDC00",
      Red: "#FD0000",
      "light-red": "#FE5959",
      "pale-red": "#FEA6A6",
      yellow: "#FEDC00",
      "light-yellow": "#FEE859",
      "pale-yellow": "#FFF3A6",
      blue: "#1674B9",
      "light-blue": "#68A5D1",
      "pale-blue": "#ADCEE7",
      white: "#F5F5F5",
    },
    fontFamily: {
      ptext: ["K2D", "sans-serif"],
      undertitle: ["Be Vietnam Pro", "sans - serif"],
      headline: ["Fredoka One", "cursive"],
    },
    extend: {},
  },
  plugins: [require("@tailwindcss/typography"), require("@tailwindcss/forms")],
};
